version: 2
enable-beta-ecosystems: true
updates:
  - directory: "/fronted"
    open-pull-requests-limit: 5
    package-ecosystem: "pub"
    rebase-strategy: auto
    schedule:
      interval: "monthly"
  - directory: "/backend"
    open-pull-requests-limit: 5
    package-ecosystem: "pub"
    rebase-strategy: auto
    schedule:
      interval: "monthly"
  - directory: "/shared"
    open-pull-requests-limit: 5
    package-ecosystem: "pub"
    rebase-strategy: auto
    schedule:
      interval: "monthly"