name: frontend
description: An absolute bare-bones web app.
version: 0.0.1
homepage: https://github.com/PlugFox/blog
repository: https://github.com/PlugFox/blog
issue_tracker: https://github.com/PlugFox/blog/issues

publish_to: none

funding:
  - https://www.buymeacoffee.com/plugfox
  - https://www.patreon.com/plugfox
  - https://boosty.to/plugfox

topics:
  - medium
  - blog
  - parser
  - selfhosted
  - sqlite

platforms:
  web:

environment:
  sdk: ^3.2.5

dependencies:
  # Utils
  meta: ^1.11.0
  intl: ^0.19.0

  # HTTP Client
  http: ^1.2.0

  # Logger
  l: 5.0.0-pre.2

  shared:
    path: ../shared

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.1.0
  test: ^1.25.1
