name: Frontend checkout

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "develop"
      - "feature/**"
      - "bugfix/**"
      - "hotfix/**"
      - "support/**"
    paths:
      - "frontend/lib/**.dart"
      - "frontend/test/**.dart"
      - "frontend/pubspec.lock"
  pull_request:
    branches:
      - "master"
      - "develop"
      - "feature/**"
      - "bugfix/**"
      - "hotfix/**"
      - "support/**"
    paths:
      - "frontend/lib/**.dart"
      - "frontend/test/**.dart"
      - "frontend/pubspec.lock"

jobs:
  checkout:
    name: "Checkout"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    container:
      image: dart:beta
    timeout-minutes: 10
    steps:
      - name: 🚂 Get latest code
        uses: actions/checkout@v3

      - name: 🚃 Cache pub modules
        uses: actions/cache@v2
        env:
          cache-name: cache-frontend-package
        with:
          path: |
            $PWD/.pub_cache/
          key: ${{ runner.os }}-frontend-${{ env.cache-name }}-${{ hashFiles('frontend/pubspec.lock') }}

      - name: 🗄️ Export pub cache directory
        run: export PUB_CACHE=$PWD/.pub_cache/

      - name: 👷 Install Dependencies
        timeout-minutes: 1
        working-directory: ${{ env.working-directory }}
        run: |
          dart pub get

      - name: 🔎 Check format
        working-directory: ${{ env.working-directory }}
        timeout-minutes: 1
        run: dart format --set-exit-if-changed -l 120 -o none lib/

      - name: 📈 Check analyzer
        working-directory: ${{ env.working-directory }}
        timeout-minutes: 1
        run: dart analyze --fatal-infos --fatal-warnings lib/

      #- name: 🧪 Run tests
      #  timeout-minutes: 2
      #  working-directory: ${{ env.working-directory }}
      #  run: |
      #    dart run coverage:test_with_coverage -fb -o coverage -- \
      #      --concurrency=6 --platform vm --coverage=./coverage --reporter=expanded test/unit_test.dart

      #- name: 📥 Upload coverage to Codecov
      #  timeout-minutes: 1
      #  uses: codecov/codecov-action@v3
      #  with:
      #    token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
